### ISSUE TITLE
Processo inverso

### ISSUE THREAD

**Issue by bigbruno** [vmath3us/stateless-arch#1]
Estou pensando a alguns dias em fazer um processo inverso, chegou a tentar algo mais ou menos assim?

Antes de atualizar cria um snapshot, atualiza e monitora a atualização, em caso de falha exibe um diálogo pedindo para reiniciar e nesse caso faz a troca para o snapshot anterior?

Com isso não seria necessário reiniciar cada vez que instalar um programa e teria uma ferramenta de restauração que parece eficaz.

**Comment by vmath3us** [comment]
não faz sentido pro escopo desse projeto. Atualizar ao vivo implica em um root com acesso de leitura e escrita acessível diretamente. Não tem uma versão 0 de todo o /etc que pode usar pra uma restauração de fábrica. Permite bagunça no /var/lib/pacman. O que você quer pode ser feito alterando o hook snap-pac pós
